### ISSUE TITLE
gapi object on gmail.com

### ISSUE THREAD

**Issue by sstefoss** [Experience-Monks/google-client-api#1]
Hi, i am trying to use your module to get the gapi object but the callback never gets called. 
I want to use your module for a plugin that runs on gmail.com. Is there a possible conflict with gmail's gapi object?

Btw. on npm install google-client-api i get version 1.0.3 on which the callback function gets called but returns "had by the snake" (which is the code from version 1.0.0 maybe?), so now i have installed 1.0.1 to work on.

Thanks!

**Comment by mikkoh** [comment]
@sstefoss one of the wierd things about the Google Client API is that it doesn't support all google apis. You can explore the apis which are supported here:
https://developers.google.com/apis-explorer/

It does look like gmail in some form or other is supported by the client api. In saying this.

I actually wrote this module out and left it because the api I wanted to use wasn't supported :(

I'll test it on my end actually write proper tests in the test folder. I'll get back to you after.

Feel free to create a PR if you have time and figure out what your issue is.

**Comment by mikkoh** [comment]
@sstefoss Your issues should be fixed in 1.0.4. That was my bad I clearly had pushed bad code when I decided to stop working on this.

I added some proper tests also so this shouldn't happen again. Thanks for the issue.

**Comment by sstefoss** [comment]
Thanks for the update.
For me, as i am running it on a chrome extension, global.$$onClientLoad function doesn't get called (maybe window.function cannot be created for security reasons). I will try to figure out. Any suggestions are welcomed.

**Comment by mikkoh** [comment]
Yeah unfortunately when using the Google Client api it uses the global callback to notify when a function changes.

Also though if you don't have access to global/window scope this library cant access the gapi object anyways if I do remember correctly.
